import React, { useRef } from 'react';

import { Component, generateGuid, makeComponent } from '@intenda/opus-ui';

export const AudioPlayer = makeComponent('audioPlayer');
export const AudioRecorder = makeComponent('audioRecorder');
export const Button = makeComponent('button');
export const Camera = makeComponent('camera');
export const Canvas = makeComponent('canvas');
export const Checkbox = makeComponent('checkbox');
export const Code = makeComponent('code');
export const DatePicker = makeComponent('datePicker');
export const Divider = makeComponent('divider');
export const FocusLine = makeComponent('focusLine');
export const Html = makeComponent('html');
export const Icon = makeComponent('icon');
export const Image = makeComponent('image');
export const Input = makeComponent('input');
export const Label = makeComponent('label');
export const MarkdownLabel = makeComponent('markdownLabel');
export const Notifications = makeComponent('notifications');
export const ProgressBar = makeComponent('progressBar');
export const Radio = makeComponent('radio');
export const Repeater = makeComponent('repeater');
export const Resizer = makeComponent('resizer');
export const Slider = makeComponent('slider');
export const Spinner = makeComponent('spinner');
export const Tab = makeComponent('tab');
export const TabContainer = makeComponent('tabContainer');
export const TimePicker = makeComponent('timePicker');
export const Treeview = makeComponent('treeview');
export const Upload = makeComponent('upload');
export const Url = makeComponent('url');
export const VideoPlayer = makeComponent('videoPlayer');
export const WebSocket = makeComponent('webSocket');